# This is a basic workflow that is triggered periodically, building docker images for P4C

name: Build-P4C-Image

on:
  schedule:
    - cron:  '0 0 * * *' # start daily at 00:00

jobs:
  solve_env: # job to run the bash command defined in 'env.p4c_commit'.
    runs-on: ubuntu-20.04
    steps:
    - name: Find latest P4C commit
      id: eval
      run: echo "::set-output name=COMMIT::`wget -qO- http://api.github.com/repos/p4lang/p4c/commits/main | grep -m1 '\"sha\"' | cut -c11-19`"
    outputs:
      LATEST_P4C_COMMIT: ${{ steps.eval.outputs.COMMIT }}

  build_matrix:
    needs: solve_env
    runs-on: ubuntu-20.04
    env:
      MAKEFLAGS: '-j2'
      DOCKER_REPO: "opennetworking/p4c"
    strategy:
      fail-fast: false # if enabled, in case of error in a matrix job, all the other jobs will be aborted.
      matrix:
          include:
          - TAGNAME: latest
            P4C_COMMIT: ${{ needs.solve_env.outputs.LATEST_P4C_COMMIT }}
            PROTOBUF_VERSION: 3.6.1
            MAKEFLAGS: $MAKEFLAGS # added MAKEFLAGS in matrix for consistency in step 'Build and export to Docker for testing'
          - TAGNAME: stable
            P4C_COMMIT: e2934ab32
            PROTOBUF_VERSION: 3.2.0
            MAKEFLAGS: $MAKEFLAGS
          - TAGNAME: stable-20210108
            P4C_COMMIT: 41b6968f8
            PROTOBUF_VERSION: 3.6.1
            MAKEFLAGS: $MAKEFLAGS
          - TAGNAME: stable-20220112
            P4C_COMMIT: e53e5fff61
            PROTOBUF_VERSION: 3.6.1
            MAKEFLAGS: $MAKEFLAGS

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker for testing.
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true # load the builded image to local docker instance. Needed for testing step.
          cache-from: "${{ env.DOCKER_REPO }}:${{ matrix.TAGNAME }}"
          build-args: |
            "PROTOBUF_VERSION=${{ matrix.PROTOBUF_VERSION }}"
            "P4C_COMMIT=${{ matrix.P4C_COMMIT }}"
            "MAKEFLAGS=${{ matrix.MAKEFLAGS }}"
          tags: "${{ env.DOCKER_REPO }}:p4c-${{ matrix.TAGNAME }}" # Local Runtime image
          target: "runtime"

      - name: Test docker build
        run: |
          docker run --rm ${{ env.DOCKER_REPO }}:p4c-${{ matrix.TAGNAME }} p4c-bm2-ss --help
          docker run --rm ${{ env.DOCKER_REPO }}:p4c-${{ matrix.TAGNAME }} p4c-graphs --help

      - name: Push to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.DOCKER_REPO }}:${{ matrix.TAGNAME }}"
          build-args: |
            "PROTOBUF_VERSION=${{ matrix.PROTOBUF_VERSION }}"
            "P4C_COMMIT=${{ matrix.P4C_COMMIT }}"
            "MAKEFLAGS=${{ matrix.MAKEFLAGS }}"
          target: "runtime"
